# Generated by Django 5.1.2 on 2024-10-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='type',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('grain', 'Grain'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('juice', 'Juice')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
